# Generated by Django 4.1.7 on 2023-03-28 16:34

from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('email_configure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', ticket.models.PrefixedSerialNumberField(max_length=12, prefix='TKT/2022/', unique=True)),
                ('query', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
                ('message_ids', models.ManyToManyField(to='email_configure.message')),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.status')),
            ],
        ),
    ]
