# Generated by Django 4.1.7 on 2023-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='custom_rate',
            field=models.CharField(choices=[('1', ''), ('2', '2')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
