# Generated by Django 4.1.7 on 2023-03-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_custom_rate_ticket_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='custom_rate',
            field=models.CharField(choices=[('satisfied', 'satisfied'), ('unsatisfied', 'unsatisfied')], max_length=20),
        ),
    ]
