# Generated by Django 4.1.7 on 2023-03-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_custom_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_rating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='custom_rate',
            field=models.CharField(choices=[('satisfied', 'Satisfied'), ('unsatisfied', 'Unsatisfied')], max_length=20),
        ),
    ]
