# Generated by Django 4.1.7 on 2023-03-29 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_rating',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
